name: Code Formatter and Linter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.10"

      - name: Install dependencies for Black and isort
        run: |
          pip install black isort

      - name: Run isort to sort imports
        run: isort .

      - name: Run Black
        run: black .

      - name: Show diff if formatting was needed
        run: |
          git diff
          exit 0

  lint:
    runs-on: ubuntu-latest
    needs: format # Ensure linting runs after formatting

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.10"

      - name: Install dependencies for Flake8
        run: pip install flake8

      - name: Run Flake8
        run: flake8 .

      - name: Show diff if linting was needed
        run: |
          git diff
          exit 0
